# Generated by Django 5.0 on 2023-12-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoodsName', models.CharField(max_length=50)),
                ('GoodsQuality', models.CharField(max_length=10)),
            ],
        ),
    ]
