# Generated by Django 5.0 on 2023-12-18 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuyerName', models.CharField(max_length=30)),
                ('MobileNumber', models.CharField(max_length=15)),
                ('FromAddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MandiExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupplierName', models.CharField(max_length=30)),
                ('MobileNumber', models.CharField(max_length=15)),
                ('FromAddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImportedGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoodsID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MainApp.goods')),
                ('SupplierID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MainApp.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='ExportedGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuyerID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MainApp.buyers')),
                ('ImportedGoodID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MainApp.importedgoods')),
            ],
        ),
    ]
