# Generated by Django 5.0 on 2023-12-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_balancesheet_buyers_mandiexpenses_suppliers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='ClosingBalance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Comment',
            field=models.TextField(blank=True, default='', help_text='Enter your comment here...', null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='OpeningBalance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='ThatDay',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='ToBank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='TodayIncome',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='TotalPaymentGiven',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='TotalPaymentReceived',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='exportedgoods',
            name='BalanceToBeReceived',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='exportedgoods',
            name='BillingStatus',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportedgoods',
            name='Comment',
            field=models.TextField(blank=True, default='', help_text='Enter your comment here...', null=True),
        ),
        migrations.AddField(
            model_name='exportedgoods',
            name='CretesCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='exportedgoods',
            name='ExportDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exportedgoods',
            name='MandiExpenses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='exportedgoods',
            name='PaymentReceivedDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='exportedgoods',
            name='SellingPrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='exportedgoods',
            name='TobeReceivedFromSupplier',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='exportedgoods',
            name='TotalAmount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='exportedgoods',
            name='inKGs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='GoodsPrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='importedgoods',
            name='BalanceToBePaid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='importedgoods',
            name='BillingStatus',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importedgoods',
            name='Comment',
            field=models.TextField(blank=True, default='', help_text='Enter your comment here...', null=True),
        ),
        migrations.AddField(
            model_name='importedgoods',
            name='DatePaid',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='importedgoods',
            name='GoodsPrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='importedgoods',
            name='ImportDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='importedgoods',
            name='MandiExpenses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='importedgoods',
            name='SoldStatus',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importedgoods',
            name='TobePaidToSupplier',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='importedgoods',
            name='TotalAmount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='importedgoods',
            name='creatsCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='importedgoods',
            name='inKGs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='mandiexpenses',
            name='Charity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='mandiexpenses',
            name='Coolie',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='mandiexpenses',
            name='MandiServiceCharge',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='mandiexpenses',
            name='Wastage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
