# Generated by Django 5.0 on 2023-12-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_yourmodel_alter_buyers_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoodsName', models.CharField(max_length=50)),
                ('FirstQualityPrice', models.IntegerField(blank=True, default=0, null=True)),
                ('SecondQualityPrice', models.IntegerField(blank=True, default=0, null=True)),
                ('RippedQualityPrice', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['GoodsName'],
            },
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
