# Generated by Django 5.0 on 2023-12-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_balancesheet_closingbalance_balancesheet_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='GoodsPrice1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
