# Generated by Django 5.0 on 2023-12-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_goods1_delete_yourmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importedgoods',
            old_name='creatsCount',
            new_name='GoodsQuantity',
        ),
        migrations.RemoveField(
            model_name='importedgoods',
            name='GoodsID',
        ),
        migrations.RemoveField(
            model_name='importedgoods',
            name='inKGs',
        ),
        migrations.AddField(
            model_name='importedgoods',
            name='GoodsNameAndQuality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='importedgoods',
            name='MeasurementUnits',
            field=models.CharField(default='Creats', max_length=50),
        ),
    ]
