# Generated by Django 5.0 on 2023-12-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_goods_goodsprice1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='GoodsPrice1',
        ),
    ]
