# Generated by Django 5.0 on 2023-12-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_rename_creatscount_importedgoods_goodsquantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedgoods',
            name='BillingStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='importedgoods',
            name='SoldStatus',
            field=models.BooleanField(default=False),
        ),
    ]
