# Generated by Django 5.0 on 2024-01-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_mandibillsummary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importedgoods',
            old_name='Comment',
            new_name='Comments',
        ),
        migrations.AddField(
            model_name='mandibillsummary',
            name='Comments',
            field=models.TextField(blank=True, default='', help_text='Enter your comment here...', null=True),
        ),
    ]
